apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002  # You can specify a custom node port or let Kubernetes assign one
  type: NodePort
